### ISSUE TITLE
Rhett Sexton Data Analysis Idea for Miniproject1

### ISSUE THREAD

**Issue by rsexton8** [wcparham1/MiniProject1#1]
Hello,

My idea is to analyze two patents from the same company. The company I had in mind is Microsoft, and I am going to look for word frequency in two of their software patents. It will be interesting to see the terms that the patent writer used the most.

**Comment by wcparham1** [comment]
I am so sorry I missed this.  I use automatic notifications from my email to track updates on my Github and must have missed the one sent from this issue. I think that is an excellent idea and you can use the example in class that looks at word frequencies between books as a sort of template.  Please let me know how it goes!  Again, I apologize for the late issue.  Did you have any product patents in mind?
